//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAPITest.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESTAPITest.Utilities.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but due to current technical issues we cannot provide a value.
        /// </summary>
        internal static string API_TIME_OUT {
            get {
                return ResourceManager.GetString("API_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but due to current technical issues we cannot provide a value.
        /// </summary>
        internal static string BAD_RESPONSE {
            get {
                return ResourceManager.GetString("BAD_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have a great morning.
        /// </summary>
        internal static string MORNING_MSG {
            get {
                return ResourceManager.GetString("MORNING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I can&apos;t find a Pension Policy that belongs to you.
        /// </summary>
        internal static string NO_PENSION_POLICY {
            get {
                return ResourceManager.GetString("NO_PENSION_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of your pension policy 1234 is £10000 as at 17/07/2017.
        /// </summary>
        internal static string ONE_IN_SCOPE_POLICY {
            get {
                return ResourceManager.GetString("ONE_IN_SCOPE_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, at the moment we can&apos;t value pension policy number 1234 using Alexa.
        /// </summary>
        internal static string OUT_OF_SCOPE_PENSION {
            get {
                return ResourceManager.GetString("OUT_OF_SCOPE_PENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pension-runway.integration.avivaaws.com:8443/api/v1/pensionPlans/TK10083228/valuations.
        /// </summary>
        internal static string PENSION_VALUATION {
            get {
                return ResourceManager.GetString("PENSION_VALUATION", resourceCulture);
            }
        }
    }
}
